CREATE TABLE IF NOT EXISTS SkillSure (
    `S_No` NUMERIC(3, 1),
    `Prorgramme_Name` VARCHAR(123) CHARACTER SET utf8,
    `Gender` VARCHAR(12) CHARACTER SET utf8,
    `State` VARCHAR(87) CHARACTER SET utf8,
    `Minimum_Age` NUMERIC(3, 1),
    `Webpage_Link` VARCHAR(187) CHARACTER SET utf8
);
INSERT INTO SkillSure VALUES
    (1.0,'Indian Leather Development Programme','Male, Female','India',0.0,'http://leatherindia.org/indian-leather-development-programme-ildp/'),
    (2.0,'Capacity Building & Technical Assistance','Male, Female','Arunachal Pradesh,  Assam, Manipur, Meghalaya, Mizoram, Nagaland, Tripura, Sikkim',0.0,'https://www.startupindia.gov.in/content/sih/en/government-schemes/CB_TA.html'),
    (3.0,'Scheme for Financial Assistance to States for Skill Development in Electronic System Design and Manufacturing (ESDM) Sector','Male, Female','Andhra Pradesh, Jammu and Kashmir, Karnataka,  Kerala, Punjab, Telangana, Uttar Pradesh',12.0,'https://esdm-skill.deity.gov.in/(S(fcqtjazhuwbxn0eqms20tjwj))/intro.aspx'),
    (4.0,'Skill Development in ESDM for Digital India','Male, Female','India',12.0,'https://esdm-skill.deity.gov.in/(S(fcqtjazhuwbxn0eqms20tjwj))/intro.aspx'),
    (5.0,'Udaan','Female','Jammu and Kashmir',18.0,'https://nsdcindia.org/udaan'),
    (6.0,'Deendayal Antyodaya Yojana - National Urban Livelihoods Mission (NULM)','Male, Female','India',18.0,'https://nulm.gov.in/'),
    (7.0,'Apprenticeship Scheme','Male, Female','India',18.0,'https://apprenticeshipindia.org/'),
    (8.0,'Vocationalization of Secondary Education','Male, Female','India',18.0,'https://www.education.gov.in/hi/vocationalisation'),
    (9.0,'Scheme of Community Development Through Polytechnics','Male, Female','India',0.0,'http://www.nitttrchd.ac.in/sitenew1/rural/rural_activity/Guideline%20Document%20on%20the%20CDTP%20Scheme.pdf'),
    (10.0,'Entrepreneurship Skill Development Programmes (ESDPs)','Male, Female','India',18.0,'https://msmedi.dcmsme.gov.in/'),
    (11.0,'Management Development Programmes (MDPs)','Male, Female','India',18.0,'https://www.shiksha.com/mdp-management-development-programme-chp'),
    (12.0,'Assistance to Training Institutions Scheme (ATI Scheme)','Male, Female','India',18.0,'https://my.msme.gov.in/MyMsmeMob/MsmeScheme/Pages/0_3_1.html'),
    (13.0,'Rural Self-Employment Training Institutes (RSETIs)','Female','India ',18.0,'http://nirdpr.org.in/rseti/'),
    (14.0,'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)','Male, Female','India ',0.0,'https://www.pmkvyofficial.org/Index.aspx'),
    (15.0,'Apprenticeship Training Scheme (ATS)','Male, Female','India',14.0,'https://www.apprenticeship.gov.in/pages/Apprenticeship/home.aspx?AspxAutoDetectCookieSupport=1'),
    (16.0,'Craftsmen Training Scheme','Male, Female','India ',14.0,'https://dgt.gov.in/CTS'),
    (17.0,'Skill Development Initiative (SDls)','Male, Female','India',14.0,'https://www.startupindia.gov.in/content/sih/en/government-schemes/SDI_.html'),
    (18.0,'Financial Assistance for Skill Training of Persons with Disabilities','Male, Female','India',15.0,'https://enabled.in/wp/financial-assistance-for-skill-training-of-persons-with-disabilities/'),
    (19.0,'Samarth (Scheme For Capacity Building In Textile Sector)','Male, Female','India',14.0,'https://samarth-textiles.gov.in/'),
    (20.0,'Scheme of Capacity Building for Service Provides','Male, Female','India ',18.0,'https://tourism.gov.in/schemes-and-guidelines/schemes/scheme-capacity-building-service-providers-institutes'),
    (21.0,'Hunar Se Rozgar Tak Initiative','Male, Female','India',18.0,'https://tourism.gov.in/sites/default/files/2020-02/Revised%20Guideline%20of%20the%20Hospitality%20training%20courses%20under%20Hunar%20SE%20Rozgar%20Tak%20amended%20upto%20%2030062019.pdf'),
    (22.0,'Vocational Training for Tribal Youth','Male, Female','India',0.0,'https://tribal.nic.in/writereaddata/Schemes/VTCGuidelinesAndApplicationFormat.pdf'),
    (23.0,'Krishi Vigyan Kendras (KVKs)','Male, Female','India',18.0,'https://icar.org.in/content/krishi-vigyan-kendra'),
    (24.0,'Support to Training and Employment Programme for Women (STEP)','Female','India ',16.0,'https://www.startupindia.gov.in/content/sih/en/government-schemes/support_to_training_and_employment_programme.html'),
    (25.0,'Jan Shikshan Sansthan','Male, Female','India',0.0,'https://jss.gov.in/');
